### ISSUE TITLE
the trait `std::marker::Send` is not implemented for `dyn futures::Future<Output = Result<(), tokio_postgres::Error>>`

### ISSUE THREAD

**Issue by bbigras** [quietboil/include-postgres-sql#2]
I wonder if it's because of `tokio_postgres::Error`.

**Comment by quietboil** [comment]
Not enough `Send` requirements. I think this is fixed now. Would you mind trying your code with the latest from GitHub?

PS: Check examples/async/bb8_pool. It works with the out of the (latest) box version of this crate. You might even not need to create a custom `impl_sql` if the pool you are using is similar to [bb8](https://github.com/djc/bb8).
